### ISSUE TITLE
[BUG #00] 정렬기준을 바꾼 뒤 뒤로가기

### ISSUE THREAD

**Issue by moonpiderman** [wafflestudio19-5/team7-web#100]
## 기대한 동작
본래 기대한(의도한) 동작을 간단히 기술해주세요.

정렬 기준을 default에서 다른 정렬기준으로 적용하고 하나의 포스트로 들어간 뒤, 뒤로가기 했을 때, 바로 정렬기준이 적용되어있을 것이라 예상했습니다.

## 현재 동작
비정상적인 현재 동작에 대해 기술해주세요.

정렬 기준이 default로 바뀝니다.

## 재현 방법
해당 버그를 재현하기 위한 방법을 기술해주세요.
2. Click on '...'
3. Scroll down to '...'

1. 정렬 기준`올해`
2. 특정 포스트로 이동
3. 뒤로가기

## 기타
필요하다면, 스크린 샷 등을 첨부해주세요.

**Comment by HyungGeun-Cho** [comment]
@moonpiderman 현재 말씀해주신대로 default로 설정되도록 한 상황입니다. 구현해보도록 하겠습니다! 감사합니다 :)
