### ISSUE TITLE
[BUG #03] 로그인 안했을 때 코멘트 작성

### ISSUE THREAD

**Issue by Arsture** [wafflestudio19-5/team7-web#102]
## 기대한 동작
로그인 안했을 때 코멘트 작성 시 로그인/회원가입으로 리다이렉션되면 좋겠습니다

## 현재 동작
토스트로 댓글 작성 오류만 뜹니다

## 재현 방법
로그인 안했을 때 코멘트 작성을 하였을 때 401 error가 아마?날 것같은데 error status를 통해 리다이렉션 시키거나 모달을 띄우면 좋을 것 같습니다

## 기타
필요하다면, 스크린 샷 등을 첨부해주세요.

**Comment by HyungGeun-Cho** [comment]
@Arsture 말씀해주신대로 추가적인 에러 처리가 필요할 것 같습니다~ 감사합니다 :)
