### ISSUE TITLE
[BUG #04] 구글 로그인시 프로파일의 이메일 주소가 짤려보입니다

### ISSUE THREAD

**Issue by d3pshot17** [wafflestudio19-5/team7-web#103]
## 현재 동작
비정상적인 현재 동작에 대해 기술해주세요.
사소하지만, 구글 로그인 시 프로파일 확인 창에서 이메일 주소의 도메인이 안보입니다.

![이멜주소](https://user-images.githubusercontent.com/83637115/148634536-ad35c32c-ae2a-408a-a0b1-03825902b01a.png)

**Comment by HyungGeun-Cho** [comment]
@d3pshot17 아 넵 맞습니다! 말씀해주신대로 개인 페이지 부분은 아직 구현 중입니다. 감사합니다!
