### ISSUE TITLE
[BUG #10] 화면 크기 조정시 사이드바 분리

### ISSUE THREAD

**Issue by JiyeonP** [wafflestudio19-5/team7-web#107]
## 기대한 동작
유저가 화면 크기를 축소하더라도 사용하기 편리한 UI가 유지되어야 합니다

## 현재 동작
게시글 페이지에서 화면 크기(글씨 크기) 작게 줄이면 사이드에 위치한 공감/공유 바, 유저 프로필 바가 화면 모서리쪽으로 멀리 떨어져 위치하는 것을 확인할 수 있습니다.

## 재현 방법
전체를 감싸는 wrapper 레이어를 만들고, 해당 레이어 안에서 컴포넌트를 구성하면 분리되지 않고 잘 작동할 것으로 보입니다.

## 기타
![image](https://user-images.githubusercontent.com/66158942/148635287-fd47e7de-8534-4da8-8270-355d9d0e4904.png)

**Comment by HyungGeun-Cho** [comment]
해결했습니다~! 감사합니다 :)
