### ISSUE TITLE
[Bug Boundty] 넓은 모니터에서 볼때 사용자 메뉴 컴포넌트위 위치가 테두리로 빠집니다.

### ISSUE THREAD

**Issue by eomiso** [wafflestudio19-5/team7-web#109]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/17143087/148637334-1e11e094-0b04-44b6-a3d8-fa00b74b63c7.png">

위 사진처럼 사용자 메뉴바가 오른쪽으로 너무 치우쳐서 보이는 문제가 생기는 군요.

제가 사용중인 모니터 해상도는 3840x2160 입니다.

PS. bug-bounty 레이블은 나중에 수정하도록 할겠습니다.

**Comment by HyungGeun-Cho** [comment]
@ongdyub style 처리완료했습니다~!
