### ISSUE TITLE
[BUG #13] 회원정보 수정에 관한 버그

### ISSUE THREAD

**Issue by kohandy1902** [wafflestudio19-5/team7-web#111]
## 기대한 동작
본인의 정보를 수정 및 회원 탈퇴를 할 수 있다.

## 현재 동작
프로필 사진, 소개 등의 수정이 불가능하고 회원탈퇴 또한 되지 않는다.

## 재현 방법
해당 버그를 재현하기 위한 방법을 기술해주세요.
1. 구글로 소셜로그인한다.
2. 설정에 들어간다.
3. 여러 버튼이 말을 듣지 않는다.

**Comment by ongdyub** [comment]
아 이거 api가 없어 구현을 못해 안먹는게 맞습니다ㅠㅠ
