### ISSUE TITLE
[BUG #01] 포스트 제목 길어지는 경우 페이지 늘어나는 것

### ISSUE THREAD

**Issue by ksiyeon27** [wafflestudio19-5/team7-web#98]
포스트 보다가 궁금증이 생겼습니다.
제목이 길어질 경우에 줄이 바뀌는 것이 아니라 오른쪽으로 페이지가 늘어나는 것이 의도된 것인가요?
velog 에서는 줄바꿈이 되는 것 같습니다!

<img width="1307" alt="스크린샷 2022-01-08 오후 2 21 20" src="https://user-images.githubusercontent.com/76062959/148632599-f50e58cb-56c8-4964-8d29-251e8e49a75e.png">

**Comment by HyungGeun-Cho** [comment]
@ksiyeon27 오 수정하겠습니다! 감사합니다 :)
