### ISSUE TITLE
[BUG #02] 구글 계정으로 소셜 로그인시 글 작성이 잘 되지 않습니다

### ISSUE THREAD

**Issue by yg-moon** [wafflestudio19-5/team7-web#99]
## 기대한 동작
- 구글 회원가입 이후 글을 작성했을 때 정상 동작.

## 현재 동작
- 글 작성시 로그인이 만료되었다고 뜹니다.
- 로그아웃 이후 다시 로그인 해봐도 똑같습니다.

## 재현 방법
해당 버그를 재현하기 위한 방법을 기술해주세요.
1. 구글 계정으로 회원가입
2. 글 작성
3. 로그인 만료

## 기타
필요하다면, 스크린 샷 등을 첨부해주세요.
<img width="1245" alt="Screen Shot 2022-01-08 at 2 34 42 PM" src="https://user-images.githubusercontent.com/56223439/148632906-6be996fc-4f84-4427-ae63-f21099046c38.png">

**Comment by ksiyeon27** [comment]
앗 저는 됩니다.
<img width="1263" alt="스크린샷 2022-01-08 오후 2 44 32" src="https://user-images.githubusercontent.com/76062959/148633144-d4c4ef90-76e5-4a3e-9fb1-4fc98c933a77.png">

**Comment by yg-moon** [comment]
브라우저 쿠키 문제인가 싶어 시크릿 모드로 다시 시도해봤지만 저는 안 되네요 ㅜㅜ
댓글 작성은 되는데 게시글 작성이 안 됩니다

**Comment by HyungGeun-Cho** [comment]
@yg-moon  한번 확인해보겠습니다! 백엔드 쪽에서의 충돌 가능성일 수도 있습니다!

**Comment by yjeong-k** [comment]
@HyungGeun-Cho 
제목을 입력하지 않으면 그렇게 뜨는 것 같아요!
저두 저렇게 떴었는데 제목 입력하니 바로 글이 작성됩니닷

**Comment by HyungGeun-Cho** [comment]
@yjeong-k 오 그렇군요..! 감사합니다!
